version: "2.4"
services:
  bot:
    build: "./bot"
    init: true
    environment:
      - "API_URL=http://server:8000"
    env_file:
      - "./bot/.env"
    depends_on:
      - "server"
  server:
    build: "./server"
    init: true
    ports:
      - "8000:8000"
      - "8001:8001"
    env_file:
      - "./server/.env"
    environment:
      DATABASE_URL: "postgresql://minigames:minigames@postgres:5432/minigames"
      JWT_PEM: "/jwt.pem"
    volumes:
      - "./server/jwt.pem:/jwt.pem"
    depends_on:
      - "database"
  postgres:
    image: "postgres:14-alpine"
    init: true
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "minigames"
      POSTGRES_PASSWORD: "minigames"
      POSTGRES_DB: "minigames"
    volumes:
      - "postgres:/var/lib/postgresql/data"
  database:
    build: "./database"
    init: true
    environment:
      DATABASE_URL: "postgresql://minigames:minigames@postgres:5432/minigames"
    depends_on:
      - "postgres"
volumes:
  postgres:
